"""
Django settings for flarebit project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['flarebit.net', 'www.flarebit.net', 'localhost', '127.0.0.1', '49.13.211.140', 'flarebit.qrme.az']

CORS_ALLOWED_ORIGINS = [
    "http://49.13.211.140",
    "http://49.13.211.140:8000",
    "https://flarebit.net",
    "https://www.flarebit.net",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://flarebit.qrme.az"
]

CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = [ 
    'https://flarebit.net', 
    'https://www.flarebit.net',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://flarebit.qrme.az'
]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1300

# SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'solo',
    'site_settings',
    'about_page',
    'blog',
    'contact_page',
    'services',
    'media_manager',
    'slider',
    'flarebit_site',
]


DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600 


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flarebit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flarebit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PG_DB'),
        'USER': os.getenv('PG_USER'),
        'PASSWORD': os.getenv('PG_PASSWORD'),
        'HOST': os.getenv('PG_HOST'),
        'PORT': os.getenv('PG_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# CKEditor Settings
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList'],
            ['Indent','Outdent'],
            ['Maximize'],
        ],
        'extraPlugins': ','.join([
            'uploadimage', # resim yükleme eklentisi
            'image2', # gelişmiş resim özellikleri
            'autolink', # URL'leri otomatik link yapma
            'autoembed', # medya içeriği gömme
            'embedsemantic', # semantik gömme
            'autogrow', # editör yüksekliğini otomatik ayarlama
        ]),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "FlareBit Admin",
    "site_header": "FlareBit",
    "site_brand": "FlareBit",
    "welcome_sign": "Welcome to FlareBit Admin",
    "copyright": "<a href='https://pashayevsproject.com'>PashayevsProject</a>",
    "search_model": ["auth.User"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_models": ["auth.Group"],
    "show_footer": False,
    "show_ui_builder": False,
    "footer_fixed": False,
    "custom_css": None,
    "custom_js": None,
    "icons": {
        "site_settings.SiteSettings": "fas fa-cogs",
        "auth.user": "fas fa-user",
        "about_page.AboutPage": "fas fa-info-circle",
        "blog.Blog": "fas fa-blog",
        "contact_page.Contact": "fas fa-envelope",
        "services.Service": "fas fa-tools",
        "media_manager.Image": "fas fa-images",
        "media_manager.Video": "fas fa-video",
        "slider.Slider": "fas fa-sliders",
        "contact_page.EmailInbox": "fas fa-inbox",
        "contact_page.Address": "fas fa-map-marker-alt",
        "contact_page.MapEmbed": "fas fa-map-marker-alt",
        "contact_page.PhoneNumber": "fas fa-phone",
        "contact_page.Email": "fas fa-envelope",
        "contact_page.ContactEmail": "fas fa-envelope",
        "contact_page.WhatsappNumber": "fab fa-whatsapp",
        "services.Service": "fas fa-tools",
    },
    "order_with_respect_to": [
        "site_settings",
        "slider",
        "about_page",
        "services",
        "blog",
        "contact_page",
        "media_manager",
        "auth",
    ],
    "related_modal_active": False
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
